// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYt8DcPUlP6y4-BFzfiEvRiw9qOwhNagI',
    appId: '1:767253469435:web:0717bcfaa629b08f63f85e',
    messagingSenderId: '767253469435',
    projectId: 'chat-app-fe9c1',
    authDomain: 'chat-app-fe9c1.firebaseapp.com',
    storageBucket: 'chat-app-fe9c1.appspot.com',
    measurementId: 'G-9CYBHE5J4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOg22CCLGIaKCaxbfMDa_R0lZoeZuVB_U',
    appId: '1:767253469435:android:6677be5d3eb93c9563f85e',
    messagingSenderId: '767253469435',
    projectId: 'chat-app-fe9c1',
    storageBucket: 'chat-app-fe9c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzU1VcwVHkjS0In1ArzlKI2GAWA-RNqU',
    appId: '1:767253469435:ios:5ad1eb3151abf60763f85e',
    messagingSenderId: '767253469435',
    projectId: 'chat-app-fe9c1',
    storageBucket: 'chat-app-fe9c1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
